<?php
define("RESPONSIVE_ADSENSE_ADCLIENT", "ca-pub-3677047087164792");
define("RESPONSIVE_ADSENSE_ADSPOT", "4842057069");
define("RESPONSIVE_ADSENSE_CUSTOM_PATH", ""); // Must contain trailing slash (/) if non-empty

define("RESPONSIVE_ADSENSE_FOLDER", "ResponsiveAdSense");
define("RESPONSIVE_ADSENSE_PATH", $_SERVER["DOCUMENT_ROOT"]."/".RESPONSIVE_ADSENSE_CUSTOM_PATH.RESPONSIVE_ADSENSE_FOLDER."/");
define("RESPONSIVE_ADSENSE_CONFIG_LOADED", true);